export const SET_START_ADDRESS = 'SET_START_ADDRESS';
export const CLEAR_ALL = 'CLEAR_ALL';
export const SET_SELECTED_FOODS = 'SET_SELECTED_FOODS';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_ONE_LIST_OF_RESTAURANTS = 'FETCH_ONE_LIST_OF_RESTAURANTS';
export const ADD_TO_RESTAURANTS_OBJECT = 'ADD_TO_RESTAURANTS_OBJECT'