export const SET_START_ADDRESS = 'SET_START_ADDRESS';
export const CLEAR_ALL = 'CLEAR_ALL';
export const SET_SELECTED_FOODS = 'SET_SELECTED_FOODS';
export const SET_ALL_RESTAURANTS = 'SET_ALL_RESTAURANTS';
export const ADD_ONE_FOOD_RESTAURANT = 'ADD_ONE_FOOD_RESTAURANT';